import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from '@mui/material';
import GlobalStyles from '@mui/material';
import theme from "../components/theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline>
              
              {children}
            </CssBaseline>
          </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
    </html>
  );
}
